// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// A2_cpp
arma::mat A2_cpp(arma::mat& mat_i, arma::mat& mat_r, arma::mat& P_i, arma::mat& P_r);
RcppExport SEXP _hdrm_A2_cpp(SEXP mat_iSEXP, SEXP mat_rSEXP, SEXP P_iSEXP, SEXP P_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type mat_i(mat_iSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mat_r(mat_rSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type P_i(P_iSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type P_r(P_rSEXP);
    rcpp_result_gen = Rcpp::wrap(A2_cpp(mat_i, mat_r, P_i, P_r));
    return rcpp_result_gen;
END_RCPP
}
// C5star_cpp
double C5star_cpp(arma::mat& X, arma::vec& group, const int B, arma::mat& TM, arma::uvec n);
RcppExport SEXP _hdrm_C5star_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP BSEXP, SEXP TMSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type TM(TMSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(C5star_cpp(X, group, B, TM, n));
    return rcpp_result_gen;
END_RCPP
}
// B3_cpp
double B3_cpp(const NumericMatrix& mat);
RcppExport SEXP _hdrm_B3_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(B3_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// B2_cpp
double B2_cpp(const NumericMatrix& mat);
RcppExport SEXP _hdrm_B2_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(B2_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// A1_cpp
double A1_cpp(const NumericMatrix& mat);
RcppExport SEXP _hdrm_A1_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(A1_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// A3_cpp
double A3_cpp(const NumericMatrix& mat, double Part6);
RcppExport SEXP _hdrm_A3_cpp(SEXP matSEXP, SEXP Part6SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type Part6(Part6SEXP);
    rcpp_result_gen = Rcpp::wrap(A3_cpp(mat, Part6));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hdrm_A2_cpp", (DL_FUNC) &_hdrm_A2_cpp, 4},
    {"_hdrm_C5star_cpp", (DL_FUNC) &_hdrm_C5star_cpp, 5},
    {"_hdrm_B3_cpp", (DL_FUNC) &_hdrm_B3_cpp, 1},
    {"_hdrm_B2_cpp", (DL_FUNC) &_hdrm_B2_cpp, 1},
    {"_hdrm_A1_cpp", (DL_FUNC) &_hdrm_A1_cpp, 1},
    {"_hdrm_A3_cpp", (DL_FUNC) &_hdrm_A3_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hdrm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
