# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A1_i_cpp <- function(mat) {
    .Call(`_hdrm_A1_i_cpp`, mat)
}

A2_ir_cpp <- function(mat1, mat2) {
    .Call(`_hdrm_A2_ir_cpp`, mat1, mat2)
}

A3_i_cpp <- function(mat) {
    .Call(`_hdrm_A3_i_cpp`, mat)
}

A1star_i_cpp <- function(mat, B) {
    .Call(`_hdrm_A1star_i_cpp`, mat, B)
}

A2star_ir_cpp <- function(mat1, mat2, B) {
    .Call(`_hdrm_A2star_ir_cpp`, mat1, mat2, B)
}

A3star_i_cpp <- function(mat, B) {
    .Call(`_hdrm_A3star_i_cpp`, mat, B)
}

C5star_cpp <- function(X_list, B) {
    .Call(`_hdrm_C5star_cpp`, X_list, B)
}

A1_i_eq_cpp <- function(mat) {
    .Call(`_hdrm_A1_i_eq_cpp`, mat)
}

A2_i_eq_cpp <- function(mat) {
    .Call(`_hdrm_A2_i_eq_cpp`, mat)
}

C1_i_eq_cpp <- function(mat) {
    .Call(`_hdrm_C1_i_eq_cpp`, mat)
}

C1star_i_eq_cpp <- function(mat, B) {
    .Call(`_hdrm_C1star_i_eq_cpp`, mat, B)
}

B0_cpp <- function(mat) {
    .Call(`_hdrm_B0_cpp`, mat)
}

B2_cpp <- function(mat) {
    .Call(`_hdrm_B2_cpp`, mat)
}

B3_cpp <- function(mat) {
    .Call(`_hdrm_B3_cpp`, mat)
}

