# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

B3_cpp <- function(mat) {
    .Call(`_hdrm_B3_cpp`, mat)
}

B2_cpp <- function(mat) {
    .Call(`_hdrm_B2_cpp`, mat)
}

A1_cpp <- function(mat) {
    .Call(`_hdrm_A1_cpp`, mat)
}

A3_cpp <- function(mat, Part6) {
    .Call(`_hdrm_A3_cpp`, mat, Part6)
}

A1star_cpp <- function(X, B) {
    .Call(`_hdrm_A1star_cpp`, X, B)
}

A2star_cpp <- function(X, Y, B) {
    .Call(`_hdrm_A2star_cpp`, X, Y, B)
}

A3star_cpp <- function(X, B) {
    .Call(`_hdrm_A3star_cpp`, X, B)
}

C5star_cpp_internal <- function(X, group, B, n) {
    .Call(`_hdrm_C5star_cpp_internal`, X, group, B, n)
}

