# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A1_eq_cpp <- function(mat) {
    .Call(`_hdrm_A1_eq_cpp`, mat)
}

A2_eq_cpp <- function(mat) {
    .Call(`_hdrm_A2_eq_cpp`, mat)
}

C1_eq_cpp <- function(mat) {
    .Call(`_hdrm_C1_eq_cpp`, mat)
}

C1_star_eq_cpp <- function(mat, B) {
    .Call(`_hdrm_C1_star_eq_cpp`, mat, B)
}

A1_cpp <- function(mat) {
    .Call(`_hdrm_A1_cpp`, mat)
}

A3_cpp <- function(mat) {
    .Call(`_hdrm_A3_cpp`, mat)
}

A1star_cpp <- function(mat, B) {
    .Call(`_hdrm_A1star_cpp`, mat, B)
}

A2star_cpp <- function(mat1, mat2, B) {
    .Call(`_hdrm_A2star_cpp`, mat1, mat2, B)
}

A3star_cpp <- function(mat, B) {
    .Call(`_hdrm_A3star_cpp`, mat, B)
}

C5star_cpp_internal <- function(X, group, B, n) {
    .Call(`_hdrm_C5star_cpp_internal`, X, group, B, n)
}

B0_cpp <- function(mat) {
    .Call(`_hdrm_B0_cpp`, mat)
}

B2_cpp <- function(mat) {
    .Call(`_hdrm_B2_cpp`, mat)
}

B3_cpp <- function(mat) {
    .Call(`_hdrm_B3_cpp`, mat)
}

